// Generated by jextract

package ua.ihromant.jnauty.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _clique_options {
 *     int *(*reorder_function)(graph_t *, boolean);
 *     int *reorder_map;
 *     boolean (*time_function)(int, int, int, int, double, double, clique_options *);
 *     FILE *output;
 *     boolean (*user_function)(set_t, graph_t *, clique_options *);
 *     void *user_data;
 *     set_t *clique_list;
 *     int clique_list_length;
 * }
 * }
 */
public class _clique_options {

    _clique_options() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        NautyTraces.C_POINTER.withName("reorder_function"),
        NautyTraces.C_POINTER.withName("reorder_map"),
        NautyTraces.C_POINTER.withName("time_function"),
        NautyTraces.C_POINTER.withName("output"),
        NautyTraces.C_POINTER.withName("user_function"),
        NautyTraces.C_POINTER.withName("user_data"),
        NautyTraces.C_POINTER.withName("clique_list"),
        NautyTraces.C_INT.withName("clique_list_length"),
        MemoryLayout.paddingLayout(4)
    ).withName("_clique_options");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * int *(*reorder_function)(graph_t *, boolean)
     * }
     */
    public final static class reorder_function {

        private reorder_function() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            NautyTraces.C_POINTER,
            NautyTraces.C_POINTER,
            NautyTraces.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NautyTraces.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout reorder_function$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("reorder_function"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *(*reorder_function)(graph_t *, boolean)
     * }
     */
    public static final AddressLayout reorder_function$layout() {
        return reorder_function$LAYOUT;
    }

    private static final long reorder_function$OFFSET = $LAYOUT.byteOffset(groupElement("reorder_function"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *(*reorder_function)(graph_t *, boolean)
     * }
     */
    public static final long reorder_function$offset() {
        return reorder_function$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *(*reorder_function)(graph_t *, boolean)
     * }
     */
    public static MemorySegment reorder_function(MemorySegment struct) {
        return struct.get(reorder_function$LAYOUT, reorder_function$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *(*reorder_function)(graph_t *, boolean)
     * }
     */
    public static void reorder_function(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(reorder_function$LAYOUT, reorder_function$OFFSET, fieldValue);
    }

    private static final AddressLayout reorder_map$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("reorder_map"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *reorder_map
     * }
     */
    public static final AddressLayout reorder_map$layout() {
        return reorder_map$LAYOUT;
    }

    private static final long reorder_map$OFFSET = $LAYOUT.byteOffset(groupElement("reorder_map"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *reorder_map
     * }
     */
    public static final long reorder_map$offset() {
        return reorder_map$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *reorder_map
     * }
     */
    public static MemorySegment reorder_map(MemorySegment struct) {
        return struct.get(reorder_map$LAYOUT, reorder_map$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *reorder_map
     * }
     */
    public static void reorder_map(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(reorder_map$LAYOUT, reorder_map$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * boolean (*time_function)(int, int, int, int, double, double, clique_options *)
     * }
     */
    public final static class time_function {

        private time_function() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(int _x0, int _x1, int _x2, int _x3, double _x4, double _x5, MemorySegment _x6);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            NautyTraces.C_INT,
            NautyTraces.C_INT,
            NautyTraces.C_INT,
            NautyTraces.C_INT,
            NautyTraces.C_INT,
            NautyTraces.C_DOUBLE,
            NautyTraces.C_DOUBLE,
            NautyTraces.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NautyTraces.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, int _x0, int _x1, int _x2, int _x3, double _x4, double _x5, MemorySegment _x6) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout time_function$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("time_function"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * boolean (*time_function)(int, int, int, int, double, double, clique_options *)
     * }
     */
    public static final AddressLayout time_function$layout() {
        return time_function$LAYOUT;
    }

    private static final long time_function$OFFSET = $LAYOUT.byteOffset(groupElement("time_function"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * boolean (*time_function)(int, int, int, int, double, double, clique_options *)
     * }
     */
    public static final long time_function$offset() {
        return time_function$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * boolean (*time_function)(int, int, int, int, double, double, clique_options *)
     * }
     */
    public static MemorySegment time_function(MemorySegment struct) {
        return struct.get(time_function$LAYOUT, time_function$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * boolean (*time_function)(int, int, int, int, double, double, clique_options *)
     * }
     */
    public static void time_function(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(time_function$LAYOUT, time_function$OFFSET, fieldValue);
    }

    private static final AddressLayout output$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("output"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * FILE *output
     * }
     */
    public static final AddressLayout output$layout() {
        return output$LAYOUT;
    }

    private static final long output$OFFSET = $LAYOUT.byteOffset(groupElement("output"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * FILE *output
     * }
     */
    public static final long output$offset() {
        return output$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * FILE *output
     * }
     */
    public static MemorySegment output(MemorySegment struct) {
        return struct.get(output$LAYOUT, output$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * FILE *output
     * }
     */
    public static void output(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(output$LAYOUT, output$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * boolean (*user_function)(set_t, graph_t *, clique_options *)
     * }
     */
    public final static class user_function {

        private user_function() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            NautyTraces.C_INT,
            NautyTraces.C_POINTER,
            NautyTraces.C_POINTER,
            NautyTraces.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NautyTraces.upcallHandle(Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout user_function$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_function"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * boolean (*user_function)(set_t, graph_t *, clique_options *)
     * }
     */
    public static final AddressLayout user_function$layout() {
        return user_function$LAYOUT;
    }

    private static final long user_function$OFFSET = $LAYOUT.byteOffset(groupElement("user_function"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * boolean (*user_function)(set_t, graph_t *, clique_options *)
     * }
     */
    public static final long user_function$offset() {
        return user_function$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * boolean (*user_function)(set_t, graph_t *, clique_options *)
     * }
     */
    public static MemorySegment user_function(MemorySegment struct) {
        return struct.get(user_function$LAYOUT, user_function$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * boolean (*user_function)(set_t, graph_t *, clique_options *)
     * }
     */
    public static void user_function(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_function$LAYOUT, user_function$OFFSET, fieldValue);
    }

    private static final AddressLayout user_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static final AddressLayout user_data$layout() {
        return user_data$LAYOUT;
    }

    private static final long user_data$OFFSET = $LAYOUT.byteOffset(groupElement("user_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static final long user_data$offset() {
        return user_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static MemorySegment user_data(MemorySegment struct) {
        return struct.get(user_data$LAYOUT, user_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static void user_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_data$LAYOUT, user_data$OFFSET, fieldValue);
    }

    private static final AddressLayout clique_list$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("clique_list"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * set_t *clique_list
     * }
     */
    public static final AddressLayout clique_list$layout() {
        return clique_list$LAYOUT;
    }

    private static final long clique_list$OFFSET = $LAYOUT.byteOffset(groupElement("clique_list"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * set_t *clique_list
     * }
     */
    public static final long clique_list$offset() {
        return clique_list$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * set_t *clique_list
     * }
     */
    public static MemorySegment clique_list(MemorySegment struct) {
        return struct.get(clique_list$LAYOUT, clique_list$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * set_t *clique_list
     * }
     */
    public static void clique_list(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(clique_list$LAYOUT, clique_list$OFFSET, fieldValue);
    }

    private static final OfInt clique_list_length$LAYOUT = (OfInt)$LAYOUT.select(groupElement("clique_list_length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int clique_list_length
     * }
     */
    public static final OfInt clique_list_length$layout() {
        return clique_list_length$LAYOUT;
    }

    private static final long clique_list_length$OFFSET = $LAYOUT.byteOffset(groupElement("clique_list_length"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int clique_list_length
     * }
     */
    public static final long clique_list_length$offset() {
        return clique_list_length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int clique_list_length
     * }
     */
    public static int clique_list_length(MemorySegment struct) {
        return struct.get(clique_list_length$LAYOUT, clique_list_length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int clique_list_length
     * }
     */
    public static void clique_list_length(MemorySegment struct, int fieldValue) {
        struct.set(clique_list_length$LAYOUT, clique_list_length$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

