// Generated by jextract

package ua.ihromant.jnauty.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _graph_t {
 *     int n;
 *     set_t *edges;
 *     int *weights;
 * }
 * }
 */
public class _graph_t {

    _graph_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        NautyTraces.C_INT.withName("n"),
        MemoryLayout.paddingLayout(4),
        NautyTraces.C_POINTER.withName("edges"),
        NautyTraces.C_POINTER.withName("weights")
    ).withName("_graph_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt n$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int n
     * }
     */
    public static final OfInt n$layout() {
        return n$LAYOUT;
    }

    private static final long n$OFFSET = $LAYOUT.byteOffset(groupElement("n"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int n
     * }
     */
    public static final long n$offset() {
        return n$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int n
     * }
     */
    public static int n(MemorySegment struct) {
        return struct.get(n$LAYOUT, n$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int n
     * }
     */
    public static void n(MemorySegment struct, int fieldValue) {
        struct.set(n$LAYOUT, n$OFFSET, fieldValue);
    }

    private static final AddressLayout edges$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("edges"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * set_t *edges
     * }
     */
    public static final AddressLayout edges$layout() {
        return edges$LAYOUT;
    }

    private static final long edges$OFFSET = $LAYOUT.byteOffset(groupElement("edges"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * set_t *edges
     * }
     */
    public static final long edges$offset() {
        return edges$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * set_t *edges
     * }
     */
    public static MemorySegment edges(MemorySegment struct) {
        return struct.get(edges$LAYOUT, edges$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * set_t *edges
     * }
     */
    public static void edges(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(edges$LAYOUT, edges$OFFSET, fieldValue);
    }

    private static final AddressLayout weights$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("weights"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *weights
     * }
     */
    public static final AddressLayout weights$layout() {
        return weights$LAYOUT;
    }

    private static final long weights$OFFSET = $LAYOUT.byteOffset(groupElement("weights"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *weights
     * }
     */
    public static final long weights$offset() {
        return weights$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *weights
     * }
     */
    public static MemorySegment weights(MemorySegment struct) {
        return struct.get(weights$LAYOUT, weights$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *weights
     * }
     */
    public static void weights(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(weights$LAYOUT, weights$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

