// Generated by jextract

package ua.ihromant.jnauty.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang=c :
 * void (*)(graph *, int *, int *, int, int, int, int *, int, boolean, int, int)
 * }
 */
public final class doref$x1 {

    private doref$x1() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, int _x3, int _x4, int _x5, MemorySegment _x6, int _x7, int _x8, int _x9, int _x10);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        nautinv_h.C_POINTER,
        nautinv_h.C_POINTER,
        nautinv_h.C_POINTER,
        nautinv_h.C_INT,
        nautinv_h.C_INT,
        nautinv_h.C_INT,
        nautinv_h.C_POINTER,
        nautinv_h.C_INT,
        nautinv_h.C_INT,
        nautinv_h.C_INT,
        nautinv_h.C_INT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = nautinv_h.upcallHandle(Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, int _x3, int _x4, int _x5, MemorySegment _x6, int _x7, int _x8, int _x9, int _x10) {
        try {
             DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6, _x7, _x8, _x9, _x10);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

