// Generated by jextract

package ua.ihromant.jnauty.ffm;

/**
 * {@snippet lang=c :
 * typedef __fpos_t fpos_t
 * }
 */
public class fpos_t extends _G_fpos_t {

    fpos_t() {
        // Should not be called directly
    }
}

