// Generated by jextract

package ua.ihromant.jnauty.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class NautyTraces extends NautyTraces_1 {

    NautyTraces() {
        // Should not be called directly
    }
    private static final long MAXRAN = -1L;
    /**
     * {@snippet lang=c :
     * #define MAXRAN -1
     * }
     */
    public static long MAXRAN() {
        return MAXRAN;
    }
    /**
     * {@snippet lang=c :
     * #define DEFEXT ".dre"
     * }
     */
    public static MemorySegment DEFEXT() {
        class Holder {
            static final MemorySegment DEFEXT
                = NautyTraces.LIBRARY_ARENA.allocateFrom(".dre");
        }
        return Holder.DEFEXT;
    }
    private static final long CLOCKS_PER_SEC = 1000000L;
    /**
     * {@snippet lang=c :
     * #define CLOCKS_PER_SEC 1000000
     * }
     */
    public static long CLOCKS_PER_SEC() {
        return CLOCKS_PER_SEC;
    }
    private static final int EWOULDBLOCK = (int)11L;
    /**
     * {@snippet lang=c :
     * #define EWOULDBLOCK 11
     * }
     */
    public static int EWOULDBLOCK() {
        return EWOULDBLOCK;
    }
    private static final int EDEADLOCK = (int)35L;
    /**
     * {@snippet lang=c :
     * #define EDEADLOCK 35
     * }
     */
    public static int EDEADLOCK() {
        return EDEADLOCK;
    }
    private static final int ENOTSUP = (int)95L;
    /**
     * {@snippet lang=c :
     * #define ENOTSUP 95
     * }
     */
    public static int ENOTSUP() {
        return ENOTSUP;
    }
    private static final MemorySegment SIG_ERR = MemorySegment.ofAddress(-1L);
    /**
     * {@snippet lang=c :
     * #define SIG_ERR (void*) -1
     * }
     */
    public static MemorySegment SIG_ERR() {
        return SIG_ERR;
    }
    private static final MemorySegment SIG_DFL = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define SIG_DFL (void*) 0
     * }
     */
    public static MemorySegment SIG_DFL() {
        return SIG_DFL;
    }
    private static final MemorySegment SIG_IGN = MemorySegment.ofAddress(1L);
    /**
     * {@snippet lang=c :
     * #define SIG_IGN (void*) 1
     * }
     */
    public static MemorySegment SIG_IGN() {
        return SIG_IGN;
    }
    private static final int SIGIO = (int)29L;
    /**
     * {@snippet lang=c :
     * #define SIGIO 29
     * }
     */
    public static int SIGIO() {
        return SIGIO;
    }
    private static final int SIGIOT = (int)6L;
    /**
     * {@snippet lang=c :
     * #define SIGIOT 6
     * }
     */
    public static int SIGIOT() {
        return SIGIOT;
    }
    private static final int SIGCLD = (int)17L;
    /**
     * {@snippet lang=c :
     * #define SIGCLD 17
     * }
     */
    public static int SIGCLD() {
        return SIGCLD;
    }
    private static final int _NSIG = (int)65L;
    /**
     * {@snippet lang=c :
     * #define _NSIG 65
     * }
     */
    public static int _NSIG() {
        return _NSIG;
    }
    private static final long __SI_PAD_SIZE = 28L;
    /**
     * {@snippet lang=c :
     * #define __SI_PAD_SIZE 28
     * }
     */
    public static long __SI_PAD_SIZE() {
        return __SI_PAD_SIZE;
    }
    private static final long __SIGEV_PAD_SIZE = 12L;
    /**
     * {@snippet lang=c :
     * #define __SIGEV_PAD_SIZE 12
     * }
     */
    public static long __SIGEV_PAD_SIZE() {
        return __SIGEV_PAD_SIZE;
    }
    private static final int NSIG = (int)65L;
    /**
     * {@snippet lang=c :
     * #define NSIG 65
     * }
     */
    public static int NSIG() {
        return NSIG;
    }
    private static final int SA_RESETHAND = (int)2147483648L;
    /**
     * {@snippet lang=c :
     * #define SA_RESETHAND 2147483648
     * }
     */
    public static int SA_RESETHAND() {
        return SA_RESETHAND;
    }
    private static final int SA_NOMASK = (int)1073741824L;
    /**
     * {@snippet lang=c :
     * #define SA_NOMASK 1073741824
     * }
     */
    public static int SA_NOMASK() {
        return SA_NOMASK;
    }
    private static final int SA_ONESHOT = (int)2147483648L;
    /**
     * {@snippet lang=c :
     * #define SA_ONESHOT 2147483648
     * }
     */
    public static int SA_ONESHOT() {
        return SA_ONESHOT;
    }
    private static final int SA_STACK = (int)134217728L;
    /**
     * {@snippet lang=c :
     * #define SA_STACK 134217728
     * }
     */
    public static int SA_STACK() {
        return SA_STACK;
    }
    private static final int FP_XSTATE_MAGIC1 = (int)1179670611L;
    /**
     * {@snippet lang=c :
     * #define FP_XSTATE_MAGIC1 1179670611
     * }
     */
    public static int FP_XSTATE_MAGIC1() {
        return FP_XSTATE_MAGIC1;
    }
    private static final int FP_XSTATE_MAGIC2 = (int)1179670597L;
    /**
     * {@snippet lang=c :
     * #define FP_XSTATE_MAGIC2 1179670597
     * }
     */
    public static int FP_XSTATE_MAGIC2() {
        return FP_XSTATE_MAGIC2;
    }
    private static final long FP_XSTATE_MAGIC2_SIZE = 4L;
    /**
     * {@snippet lang=c :
     * #define FP_XSTATE_MAGIC2_SIZE 4
     * }
     */
    public static long FP_XSTATE_MAGIC2_SIZE() {
        return FP_XSTATE_MAGIC2_SIZE;
    }
    private static final int NGREG = (int)23L;
    /**
     * {@snippet lang=c :
     * #define NGREG 23
     * }
     */
    public static int NGREG() {
        return NGREG;
    }
    private static final int WCOREFLAG = (int)128L;
    /**
     * {@snippet lang=c :
     * #define WCOREFLAG 128
     * }
     */
    public static int WCOREFLAG() {
        return WCOREFLAG;
    }
    private static final int WAIT_ANY = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define WAIT_ANY -1
     * }
     */
    public static int WAIT_ANY() {
        return WAIT_ANY;
    }
    /**
     * {@snippet lang=c :
     * #define GRAPH6_HEADER ">>graph6<<"
     * }
     */
    public static MemorySegment GRAPH6_HEADER() {
        class Holder {
            static final MemorySegment GRAPH6_HEADER
                = NautyTraces.LIBRARY_ARENA.allocateFrom(">>graph6<<");
        }
        return Holder.GRAPH6_HEADER;
    }
    /**
     * {@snippet lang=c :
     * #define SPARSE6_HEADER ">>sparse6<<"
     * }
     */
    public static MemorySegment SPARSE6_HEADER() {
        class Holder {
            static final MemorySegment SPARSE6_HEADER
                = NautyTraces.LIBRARY_ARENA.allocateFrom(">>sparse6<<");
        }
        return Holder.SPARSE6_HEADER;
    }
    /**
     * {@snippet lang=c :
     * #define DIGRAPH6_HEADER ">>digraph6<<"
     * }
     */
    public static MemorySegment DIGRAPH6_HEADER() {
        class Holder {
            static final MemorySegment DIGRAPH6_HEADER
                = NautyTraces.LIBRARY_ARENA.allocateFrom(">>digraph6<<");
        }
        return Holder.DIGRAPH6_HEADER;
    }
    /**
     * {@snippet lang=c :
     * #define PLANARCODE_HEADER ">>planar_code<<"
     * }
     */
    public static MemorySegment PLANARCODE_HEADER() {
        class Holder {
            static final MemorySegment PLANARCODE_HEADER
                = NautyTraces.LIBRARY_ARENA.allocateFrom(">>planar_code<<");
        }
        return Holder.PLANARCODE_HEADER;
    }
    /**
     * {@snippet lang=c :
     * #define PLANARCODELE_HEADER ">>planar_code le<<"
     * }
     */
    public static MemorySegment PLANARCODELE_HEADER() {
        class Holder {
            static final MemorySegment PLANARCODELE_HEADER
                = NautyTraces.LIBRARY_ARENA.allocateFrom(">>planar_code le<<");
        }
        return Holder.PLANARCODELE_HEADER;
    }
    /**
     * {@snippet lang=c :
     * #define PLANARCODEBE_HEADER ">>planar_code be<<"
     * }
     */
    public static MemorySegment PLANARCODEBE_HEADER() {
        class Holder {
            static final MemorySegment PLANARCODEBE_HEADER
                = NautyTraces.LIBRARY_ARENA.allocateFrom(">>planar_code be<<");
        }
        return Holder.PLANARCODEBE_HEADER;
    }
    /**
     * {@snippet lang=c :
     * #define EDGECODE_HEADER ">>edge_code<<"
     * }
     */
    public static MemorySegment EDGECODE_HEADER() {
        class Holder {
            static final MemorySegment EDGECODE_HEADER
                = NautyTraces.LIBRARY_ARENA.allocateFrom(">>edge_code<<");
        }
        return Holder.EDGECODE_HEADER;
    }
    private static final int PLANARCODEANY = (int)28L;
    /**
     * {@snippet lang=c :
     * #define PLANARCODEANY 28
     * }
     */
    public static int PLANARCODEANY() {
        return PLANARCODEANY;
    }
    private static final long MAXARG = 2140000000L;
    /**
     * {@snippet lang=c :
     * #define MAXARG 2140000000
     * }
     */
    public static long MAXARG() {
        return MAXARG;
    }
    private static final long NOLIMIT = 2140000031L;
    /**
     * {@snippet lang=c :
     * #define NOLIMIT 2140000031
     * }
     */
    public static long NOLIMIT() {
        return NOLIMIT;
    }
    private static final long MAXLONGARG = 9220000000000000000L;
    /**
     * {@snippet lang=c :
     * #define MAXLONGARG 9220000000000000000
     * }
     */
    public static long MAXLONGARG() {
        return MAXLONGARG;
    }
}

