// Generated by jextract

package ua.ihromant.jnauty.ffm;

/**
 * {@snippet lang=c :
 * typedef struct optionstruct {
 *     int getcanon;
 *     boolean digraph;
 *     boolean writeautoms;
 *     boolean writemarkers;
 *     boolean defaultptn;
 *     boolean cartesian;
 *     int linelength;
 *     FILE *outfile;
 *     void (*userrefproc)(graph *, int *, int *, int, int *, int *, set *, int *, int, int);
 *     void (*userautomproc)(int, int *, int *, int, int, int);
 *     void (*userlevelproc)(int *, int *, int, int *, statsblk *, int, int, int, int, int, int);
 *     void (*usernodeproc)(graph *, int *, int *, int, int, int, int, int, int);
 *     int (*usercanonproc)(graph *, int *, graph *, unsigned long, int, int, int);
 *     void (*invarproc)(graph *, int *, int *, int, int, int, int *, int, boolean, int, int);
 *     int tc_level;
 *     int mininvarlevel;
 *     int maxinvarlevel;
 *     int invararg;
 *     dispatchvec *dispatch;
 *     boolean schreier;
 *     void *extra_options;
 * } optionblk
 * }
 */
public class optionblk extends optionstruct {

    optionblk() {
        // Should not be called directly
    }
}

