// Generated by jextract

package ua.ihromant.jnauty.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct permnodestruct {
 *     struct permnodestruct *prev;
 *     struct permnodestruct *next;
 *     unsigned long refcount;
 *     int nalloc;
 *     int mark;
 *     int p[];
 * }
 * }
 */
public class permnodestruct {

    permnodestruct() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        NautyTraces.C_POINTER.withName("prev"),
        NautyTraces.C_POINTER.withName("next"),
        NautyTraces.C_LONG.withName("refcount"),
        NautyTraces.C_INT.withName("nalloc"),
        NautyTraces.C_INT.withName("mark"),
        MemoryLayout.sequenceLayout(0, NautyTraces.C_INT).withName("p")
    ).withName("permnodestruct");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout prev$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("prev"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct permnodestruct *prev
     * }
     */
    public static final AddressLayout prev$layout() {
        return prev$LAYOUT;
    }

    private static final long prev$OFFSET = $LAYOUT.byteOffset(groupElement("prev"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct permnodestruct *prev
     * }
     */
    public static final long prev$offset() {
        return prev$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct permnodestruct *prev
     * }
     */
    public static MemorySegment prev(MemorySegment struct) {
        return struct.get(prev$LAYOUT, prev$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct permnodestruct *prev
     * }
     */
    public static void prev(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(prev$LAYOUT, prev$OFFSET, fieldValue);
    }

    private static final AddressLayout next$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("next"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct permnodestruct *next
     * }
     */
    public static final AddressLayout next$layout() {
        return next$LAYOUT;
    }

    private static final long next$OFFSET = $LAYOUT.byteOffset(groupElement("next"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct permnodestruct *next
     * }
     */
    public static final long next$offset() {
        return next$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct permnodestruct *next
     * }
     */
    public static MemorySegment next(MemorySegment struct) {
        return struct.get(next$LAYOUT, next$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct permnodestruct *next
     * }
     */
    public static void next(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(next$LAYOUT, next$OFFSET, fieldValue);
    }

    private static final OfLong refcount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("refcount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long refcount
     * }
     */
    public static final OfLong refcount$layout() {
        return refcount$LAYOUT;
    }

    private static final long refcount$OFFSET = $LAYOUT.byteOffset(groupElement("refcount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long refcount
     * }
     */
    public static final long refcount$offset() {
        return refcount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long refcount
     * }
     */
    public static long refcount(MemorySegment struct) {
        return struct.get(refcount$LAYOUT, refcount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long refcount
     * }
     */
    public static void refcount(MemorySegment struct, long fieldValue) {
        struct.set(refcount$LAYOUT, refcount$OFFSET, fieldValue);
    }

    private static final OfInt nalloc$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nalloc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int nalloc
     * }
     */
    public static final OfInt nalloc$layout() {
        return nalloc$LAYOUT;
    }

    private static final long nalloc$OFFSET = $LAYOUT.byteOffset(groupElement("nalloc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int nalloc
     * }
     */
    public static final long nalloc$offset() {
        return nalloc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int nalloc
     * }
     */
    public static int nalloc(MemorySegment struct) {
        return struct.get(nalloc$LAYOUT, nalloc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int nalloc
     * }
     */
    public static void nalloc(MemorySegment struct, int fieldValue) {
        struct.set(nalloc$LAYOUT, nalloc$OFFSET, fieldValue);
    }

    private static final OfInt mark$LAYOUT = (OfInt)$LAYOUT.select(groupElement("mark"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int mark
     * }
     */
    public static final OfInt mark$layout() {
        return mark$LAYOUT;
    }

    private static final long mark$OFFSET = $LAYOUT.byteOffset(groupElement("mark"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int mark
     * }
     */
    public static final long mark$offset() {
        return mark$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int mark
     * }
     */
    public static int mark(MemorySegment struct) {
        return struct.get(mark$LAYOUT, mark$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int mark
     * }
     */
    public static void mark(MemorySegment struct, int fieldValue) {
        struct.set(mark$LAYOUT, mark$OFFSET, fieldValue);
    }

    private static final SequenceLayout p$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("p"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int p[]
     * }
     */
    public static final SequenceLayout p$layout() {
        return p$LAYOUT;
    }

    private static final long p$OFFSET = $LAYOUT.byteOffset(groupElement("p"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int p[]
     * }
     */
    public static final long p$offset() {
        return p$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int p[]
     * }
     */
    public static MemorySegment p(MemorySegment struct) {
        return struct.asSlice(p$OFFSET, p$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int p[]
     * }
     */
    public static void p(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, p$OFFSET, p$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

