// Generated by jextract

package ua.ihromant.jnauty.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct permnodestruct {
 *     struct permnodestruct *prev;
 *     struct permnodestruct *next;
 *     unsigned long refcount;
 *     int nalloc;
 *     int mark;
 *     int p[];
 * } permnode
 * }
 */
public class permnode extends permnodestruct {

    permnode() {
        // Should not be called directly
    }
}

