// Generated by jextract

package ua.ihromant.jnauty.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct schreierlevel {
 *     struct schreierlevel *next;
 *     int fixed;
 *     int nalloc;
 *     permnode **vec;
 *     int *pwr;
 *     int *orbits;
 *     permnode *marker;
 * }
 * }
 */
public class schreierlevel {

    schreierlevel() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        NautyTraces.C_POINTER.withName("next"),
        NautyTraces.C_INT.withName("fixed"),
        NautyTraces.C_INT.withName("nalloc"),
        NautyTraces.C_POINTER.withName("vec"),
        NautyTraces.C_POINTER.withName("pwr"),
        NautyTraces.C_POINTER.withName("orbits"),
        NautyTraces.C_POINTER.withName("marker")
    ).withName("schreierlevel");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout next$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("next"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct schreierlevel *next
     * }
     */
    public static final AddressLayout next$layout() {
        return next$LAYOUT;
    }

    private static final long next$OFFSET = $LAYOUT.byteOffset(groupElement("next"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct schreierlevel *next
     * }
     */
    public static final long next$offset() {
        return next$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct schreierlevel *next
     * }
     */
    public static MemorySegment next(MemorySegment struct) {
        return struct.get(next$LAYOUT, next$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct schreierlevel *next
     * }
     */
    public static void next(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(next$LAYOUT, next$OFFSET, fieldValue);
    }

    private static final OfInt fixed$LAYOUT = (OfInt)$LAYOUT.select(groupElement("fixed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int fixed
     * }
     */
    public static final OfInt fixed$layout() {
        return fixed$LAYOUT;
    }

    private static final long fixed$OFFSET = $LAYOUT.byteOffset(groupElement("fixed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int fixed
     * }
     */
    public static final long fixed$offset() {
        return fixed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int fixed
     * }
     */
    public static int fixed(MemorySegment struct) {
        return struct.get(fixed$LAYOUT, fixed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int fixed
     * }
     */
    public static void fixed(MemorySegment struct, int fieldValue) {
        struct.set(fixed$LAYOUT, fixed$OFFSET, fieldValue);
    }

    private static final OfInt nalloc$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nalloc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int nalloc
     * }
     */
    public static final OfInt nalloc$layout() {
        return nalloc$LAYOUT;
    }

    private static final long nalloc$OFFSET = $LAYOUT.byteOffset(groupElement("nalloc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int nalloc
     * }
     */
    public static final long nalloc$offset() {
        return nalloc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int nalloc
     * }
     */
    public static int nalloc(MemorySegment struct) {
        return struct.get(nalloc$LAYOUT, nalloc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int nalloc
     * }
     */
    public static void nalloc(MemorySegment struct, int fieldValue) {
        struct.set(nalloc$LAYOUT, nalloc$OFFSET, fieldValue);
    }

    private static final AddressLayout vec$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("vec"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * permnode **vec
     * }
     */
    public static final AddressLayout vec$layout() {
        return vec$LAYOUT;
    }

    private static final long vec$OFFSET = $LAYOUT.byteOffset(groupElement("vec"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * permnode **vec
     * }
     */
    public static final long vec$offset() {
        return vec$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * permnode **vec
     * }
     */
    public static MemorySegment vec(MemorySegment struct) {
        return struct.get(vec$LAYOUT, vec$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * permnode **vec
     * }
     */
    public static void vec(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(vec$LAYOUT, vec$OFFSET, fieldValue);
    }

    private static final AddressLayout pwr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pwr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *pwr
     * }
     */
    public static final AddressLayout pwr$layout() {
        return pwr$LAYOUT;
    }

    private static final long pwr$OFFSET = $LAYOUT.byteOffset(groupElement("pwr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *pwr
     * }
     */
    public static final long pwr$offset() {
        return pwr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *pwr
     * }
     */
    public static MemorySegment pwr(MemorySegment struct) {
        return struct.get(pwr$LAYOUT, pwr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *pwr
     * }
     */
    public static void pwr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pwr$LAYOUT, pwr$OFFSET, fieldValue);
    }

    private static final AddressLayout orbits$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("orbits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *orbits
     * }
     */
    public static final AddressLayout orbits$layout() {
        return orbits$LAYOUT;
    }

    private static final long orbits$OFFSET = $LAYOUT.byteOffset(groupElement("orbits"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *orbits
     * }
     */
    public static final long orbits$offset() {
        return orbits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *orbits
     * }
     */
    public static MemorySegment orbits(MemorySegment struct) {
        return struct.get(orbits$LAYOUT, orbits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *orbits
     * }
     */
    public static void orbits(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(orbits$LAYOUT, orbits$OFFSET, fieldValue);
    }

    private static final AddressLayout marker$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("marker"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * permnode *marker
     * }
     */
    public static final AddressLayout marker$layout() {
        return marker$LAYOUT;
    }

    private static final long marker$OFFSET = $LAYOUT.byteOffset(groupElement("marker"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * permnode *marker
     * }
     */
    public static final long marker$offset() {
        return marker$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * permnode *marker
     * }
     */
    public static MemorySegment marker(MemorySegment struct) {
        return struct.get(marker$LAYOUT, marker$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * permnode *marker
     * }
     */
    public static void marker(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(marker$LAYOUT, marker$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

