// Generated by jextract

package ua.ihromant.jnauty.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct schreierlevel {
 *     struct schreierlevel *next;
 *     int fixed;
 *     int nalloc;
 *     permnode **vec;
 *     int *pwr;
 *     int *orbits;
 *     permnode *marker;
 * } schreier
 * }
 */
public class schreier extends schreierlevel {

    schreier() {
        // Should not be called directly
    }
}

