// Generated by jextract

package ua.ihromant.jnauty.ffm;

/**
 * {@snippet lang=c :
 * typedef __sigset_t sigset_t
 * }
 */
public class sigset_t extends __sigset_t {

    sigset_t() {
        // Should not be called directly
    }
}

