// Generated by jextract

package ua.ihromant.jnauty.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     size_t nde;
 *     size_t *v;
 *     int nv;
 *     int *d;
 *     int *e;
 *     sg_weight *w;
 *     size_t vlen;
 *     size_t dlen;
 *     size_t elen;
 *     size_t wlen;
 * }
 * }
 */
public class sparsegraph {

    sparsegraph() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        NautyTraces.C_LONG.withName("nde"),
        NautyTraces.C_POINTER.withName("v"),
        NautyTraces.C_INT.withName("nv"),
        MemoryLayout.paddingLayout(4),
        NautyTraces.C_POINTER.withName("d"),
        NautyTraces.C_POINTER.withName("e"),
        NautyTraces.C_POINTER.withName("w"),
        NautyTraces.C_LONG.withName("vlen"),
        NautyTraces.C_LONG.withName("dlen"),
        NautyTraces.C_LONG.withName("elen"),
        NautyTraces.C_LONG.withName("wlen")
    ).withName("$anon$39:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong nde$LAYOUT = (OfLong)$LAYOUT.select(groupElement("nde"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t nde
     * }
     */
    public static final OfLong nde$layout() {
        return nde$LAYOUT;
    }

    private static final long nde$OFFSET = $LAYOUT.byteOffset(groupElement("nde"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t nde
     * }
     */
    public static final long nde$offset() {
        return nde$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t nde
     * }
     */
    public static long nde(MemorySegment struct) {
        return struct.get(nde$LAYOUT, nde$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t nde
     * }
     */
    public static void nde(MemorySegment struct, long fieldValue) {
        struct.set(nde$LAYOUT, nde$OFFSET, fieldValue);
    }

    private static final AddressLayout v$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("v"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t *v
     * }
     */
    public static final AddressLayout v$layout() {
        return v$LAYOUT;
    }

    private static final long v$OFFSET = $LAYOUT.byteOffset(groupElement("v"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t *v
     * }
     */
    public static final long v$offset() {
        return v$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t *v
     * }
     */
    public static MemorySegment v(MemorySegment struct) {
        return struct.get(v$LAYOUT, v$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t *v
     * }
     */
    public static void v(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(v$LAYOUT, v$OFFSET, fieldValue);
    }

    private static final OfInt nv$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int nv
     * }
     */
    public static final OfInt nv$layout() {
        return nv$LAYOUT;
    }

    private static final long nv$OFFSET = $LAYOUT.byteOffset(groupElement("nv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int nv
     * }
     */
    public static final long nv$offset() {
        return nv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int nv
     * }
     */
    public static int nv(MemorySegment struct) {
        return struct.get(nv$LAYOUT, nv$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int nv
     * }
     */
    public static void nv(MemorySegment struct, int fieldValue) {
        struct.set(nv$LAYOUT, nv$OFFSET, fieldValue);
    }

    private static final AddressLayout d$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("d"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *d
     * }
     */
    public static final AddressLayout d$layout() {
        return d$LAYOUT;
    }

    private static final long d$OFFSET = $LAYOUT.byteOffset(groupElement("d"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *d
     * }
     */
    public static final long d$offset() {
        return d$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *d
     * }
     */
    public static MemorySegment d(MemorySegment struct) {
        return struct.get(d$LAYOUT, d$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *d
     * }
     */
    public static void d(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(d$LAYOUT, d$OFFSET, fieldValue);
    }

    private static final AddressLayout e$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("e"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *e
     * }
     */
    public static final AddressLayout e$layout() {
        return e$LAYOUT;
    }

    private static final long e$OFFSET = $LAYOUT.byteOffset(groupElement("e"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *e
     * }
     */
    public static final long e$offset() {
        return e$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *e
     * }
     */
    public static MemorySegment e(MemorySegment struct) {
        return struct.get(e$LAYOUT, e$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *e
     * }
     */
    public static void e(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(e$LAYOUT, e$OFFSET, fieldValue);
    }

    private static final AddressLayout w$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("w"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * sg_weight *w
     * }
     */
    public static final AddressLayout w$layout() {
        return w$LAYOUT;
    }

    private static final long w$OFFSET = $LAYOUT.byteOffset(groupElement("w"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * sg_weight *w
     * }
     */
    public static final long w$offset() {
        return w$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * sg_weight *w
     * }
     */
    public static MemorySegment w(MemorySegment struct) {
        return struct.get(w$LAYOUT, w$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * sg_weight *w
     * }
     */
    public static void w(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(w$LAYOUT, w$OFFSET, fieldValue);
    }

    private static final OfLong vlen$LAYOUT = (OfLong)$LAYOUT.select(groupElement("vlen"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t vlen
     * }
     */
    public static final OfLong vlen$layout() {
        return vlen$LAYOUT;
    }

    private static final long vlen$OFFSET = $LAYOUT.byteOffset(groupElement("vlen"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t vlen
     * }
     */
    public static final long vlen$offset() {
        return vlen$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t vlen
     * }
     */
    public static long vlen(MemorySegment struct) {
        return struct.get(vlen$LAYOUT, vlen$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t vlen
     * }
     */
    public static void vlen(MemorySegment struct, long fieldValue) {
        struct.set(vlen$LAYOUT, vlen$OFFSET, fieldValue);
    }

    private static final OfLong dlen$LAYOUT = (OfLong)$LAYOUT.select(groupElement("dlen"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t dlen
     * }
     */
    public static final OfLong dlen$layout() {
        return dlen$LAYOUT;
    }

    private static final long dlen$OFFSET = $LAYOUT.byteOffset(groupElement("dlen"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t dlen
     * }
     */
    public static final long dlen$offset() {
        return dlen$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t dlen
     * }
     */
    public static long dlen(MemorySegment struct) {
        return struct.get(dlen$LAYOUT, dlen$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t dlen
     * }
     */
    public static void dlen(MemorySegment struct, long fieldValue) {
        struct.set(dlen$LAYOUT, dlen$OFFSET, fieldValue);
    }

    private static final OfLong elen$LAYOUT = (OfLong)$LAYOUT.select(groupElement("elen"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t elen
     * }
     */
    public static final OfLong elen$layout() {
        return elen$LAYOUT;
    }

    private static final long elen$OFFSET = $LAYOUT.byteOffset(groupElement("elen"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t elen
     * }
     */
    public static final long elen$offset() {
        return elen$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t elen
     * }
     */
    public static long elen(MemorySegment struct) {
        return struct.get(elen$LAYOUT, elen$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t elen
     * }
     */
    public static void elen(MemorySegment struct, long fieldValue) {
        struct.set(elen$LAYOUT, elen$OFFSET, fieldValue);
    }

    private static final OfLong wlen$LAYOUT = (OfLong)$LAYOUT.select(groupElement("wlen"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t wlen
     * }
     */
    public static final OfLong wlen$layout() {
        return wlen$LAYOUT;
    }

    private static final long wlen$OFFSET = $LAYOUT.byteOffset(groupElement("wlen"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t wlen
     * }
     */
    public static final long wlen$offset() {
        return wlen$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t wlen
     * }
     */
    public static long wlen(MemorySegment struct) {
        return struct.get(wlen$LAYOUT, wlen$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t wlen
     * }
     */
    public static void wlen(MemorySegment struct, long fieldValue) {
        struct.set(wlen$LAYOUT, wlen$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

