// Generated by jextract

package ua.ihromant.jnauty.ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@snippet lang=c :
 * struct {
 *     double grpsize1;
 *     int grpsize2;
 *     int numorbits;
 *     int numgenerators;
 *     int errstatus;
 *     unsigned long numnodes;
 *     unsigned long numbadleaves;
 *     int maxlevel;
 *     unsigned long tctotal;
 *     unsigned long canupdates;
 *     unsigned long invapplics;
 *     unsigned long invsuccesses;
 *     int invarsuclevel;
 * }
 * }
 */
public class statsblk {

    statsblk() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        nautinv_h.C_DOUBLE.withName("grpsize1"),
        nautinv_h.C_INT.withName("grpsize2"),
        nautinv_h.C_INT.withName("numorbits"),
        nautinv_h.C_INT.withName("numgenerators"),
        nautinv_h.C_INT.withName("errstatus"),
        nautinv_h.C_LONG.withName("numnodes"),
        nautinv_h.C_LONG.withName("numbadleaves"),
        nautinv_h.C_INT.withName("maxlevel"),
        MemoryLayout.paddingLayout(4),
        nautinv_h.C_LONG.withName("tctotal"),
        nautinv_h.C_LONG.withName("canupdates"),
        nautinv_h.C_LONG.withName("invapplics"),
        nautinv_h.C_LONG.withName("invsuccesses"),
        nautinv_h.C_INT.withName("invarsuclevel"),
        MemoryLayout.paddingLayout(4)
    ).withName("$anon$1118:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble grpsize1$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("grpsize1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double grpsize1
     * }
     */
    public static final OfDouble grpsize1$layout() {
        return grpsize1$LAYOUT;
    }

    private static final long grpsize1$OFFSET = $LAYOUT.byteOffset(groupElement("grpsize1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double grpsize1
     * }
     */
    public static final long grpsize1$offset() {
        return grpsize1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double grpsize1
     * }
     */
    public static double grpsize1(MemorySegment struct) {
        return struct.get(grpsize1$LAYOUT, grpsize1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double grpsize1
     * }
     */
    public static void grpsize1(MemorySegment struct, double fieldValue) {
        struct.set(grpsize1$LAYOUT, grpsize1$OFFSET, fieldValue);
    }

    private static final OfInt grpsize2$LAYOUT = (OfInt)$LAYOUT.select(groupElement("grpsize2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int grpsize2
     * }
     */
    public static final OfInt grpsize2$layout() {
        return grpsize2$LAYOUT;
    }

    private static final long grpsize2$OFFSET = $LAYOUT.byteOffset(groupElement("grpsize2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int grpsize2
     * }
     */
    public static final long grpsize2$offset() {
        return grpsize2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int grpsize2
     * }
     */
    public static int grpsize2(MemorySegment struct) {
        return struct.get(grpsize2$LAYOUT, grpsize2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int grpsize2
     * }
     */
    public static void grpsize2(MemorySegment struct, int fieldValue) {
        struct.set(grpsize2$LAYOUT, grpsize2$OFFSET, fieldValue);
    }

    private static final OfInt numorbits$LAYOUT = (OfInt)$LAYOUT.select(groupElement("numorbits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int numorbits
     * }
     */
    public static final OfInt numorbits$layout() {
        return numorbits$LAYOUT;
    }

    private static final long numorbits$OFFSET = $LAYOUT.byteOffset(groupElement("numorbits"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int numorbits
     * }
     */
    public static final long numorbits$offset() {
        return numorbits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int numorbits
     * }
     */
    public static int numorbits(MemorySegment struct) {
        return struct.get(numorbits$LAYOUT, numorbits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int numorbits
     * }
     */
    public static void numorbits(MemorySegment struct, int fieldValue) {
        struct.set(numorbits$LAYOUT, numorbits$OFFSET, fieldValue);
    }

    private static final OfInt numgenerators$LAYOUT = (OfInt)$LAYOUT.select(groupElement("numgenerators"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int numgenerators
     * }
     */
    public static final OfInt numgenerators$layout() {
        return numgenerators$LAYOUT;
    }

    private static final long numgenerators$OFFSET = $LAYOUT.byteOffset(groupElement("numgenerators"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int numgenerators
     * }
     */
    public static final long numgenerators$offset() {
        return numgenerators$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int numgenerators
     * }
     */
    public static int numgenerators(MemorySegment struct) {
        return struct.get(numgenerators$LAYOUT, numgenerators$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int numgenerators
     * }
     */
    public static void numgenerators(MemorySegment struct, int fieldValue) {
        struct.set(numgenerators$LAYOUT, numgenerators$OFFSET, fieldValue);
    }

    private static final OfInt errstatus$LAYOUT = (OfInt)$LAYOUT.select(groupElement("errstatus"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int errstatus
     * }
     */
    public static final OfInt errstatus$layout() {
        return errstatus$LAYOUT;
    }

    private static final long errstatus$OFFSET = $LAYOUT.byteOffset(groupElement("errstatus"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int errstatus
     * }
     */
    public static final long errstatus$offset() {
        return errstatus$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int errstatus
     * }
     */
    public static int errstatus(MemorySegment struct) {
        return struct.get(errstatus$LAYOUT, errstatus$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int errstatus
     * }
     */
    public static void errstatus(MemorySegment struct, int fieldValue) {
        struct.set(errstatus$LAYOUT, errstatus$OFFSET, fieldValue);
    }

    private static final OfLong numnodes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("numnodes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long numnodes
     * }
     */
    public static final OfLong numnodes$layout() {
        return numnodes$LAYOUT;
    }

    private static final long numnodes$OFFSET = $LAYOUT.byteOffset(groupElement("numnodes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long numnodes
     * }
     */
    public static final long numnodes$offset() {
        return numnodes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long numnodes
     * }
     */
    public static long numnodes(MemorySegment struct) {
        return struct.get(numnodes$LAYOUT, numnodes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long numnodes
     * }
     */
    public static void numnodes(MemorySegment struct, long fieldValue) {
        struct.set(numnodes$LAYOUT, numnodes$OFFSET, fieldValue);
    }

    private static final OfLong numbadleaves$LAYOUT = (OfLong)$LAYOUT.select(groupElement("numbadleaves"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long numbadleaves
     * }
     */
    public static final OfLong numbadleaves$layout() {
        return numbadleaves$LAYOUT;
    }

    private static final long numbadleaves$OFFSET = $LAYOUT.byteOffset(groupElement("numbadleaves"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long numbadleaves
     * }
     */
    public static final long numbadleaves$offset() {
        return numbadleaves$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long numbadleaves
     * }
     */
    public static long numbadleaves(MemorySegment struct) {
        return struct.get(numbadleaves$LAYOUT, numbadleaves$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long numbadleaves
     * }
     */
    public static void numbadleaves(MemorySegment struct, long fieldValue) {
        struct.set(numbadleaves$LAYOUT, numbadleaves$OFFSET, fieldValue);
    }

    private static final OfInt maxlevel$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maxlevel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int maxlevel
     * }
     */
    public static final OfInt maxlevel$layout() {
        return maxlevel$LAYOUT;
    }

    private static final long maxlevel$OFFSET = $LAYOUT.byteOffset(groupElement("maxlevel"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int maxlevel
     * }
     */
    public static final long maxlevel$offset() {
        return maxlevel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int maxlevel
     * }
     */
    public static int maxlevel(MemorySegment struct) {
        return struct.get(maxlevel$LAYOUT, maxlevel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int maxlevel
     * }
     */
    public static void maxlevel(MemorySegment struct, int fieldValue) {
        struct.set(maxlevel$LAYOUT, maxlevel$OFFSET, fieldValue);
    }

    private static final OfLong tctotal$LAYOUT = (OfLong)$LAYOUT.select(groupElement("tctotal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long tctotal
     * }
     */
    public static final OfLong tctotal$layout() {
        return tctotal$LAYOUT;
    }

    private static final long tctotal$OFFSET = $LAYOUT.byteOffset(groupElement("tctotal"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long tctotal
     * }
     */
    public static final long tctotal$offset() {
        return tctotal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long tctotal
     * }
     */
    public static long tctotal(MemorySegment struct) {
        return struct.get(tctotal$LAYOUT, tctotal$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long tctotal
     * }
     */
    public static void tctotal(MemorySegment struct, long fieldValue) {
        struct.set(tctotal$LAYOUT, tctotal$OFFSET, fieldValue);
    }

    private static final OfLong canupdates$LAYOUT = (OfLong)$LAYOUT.select(groupElement("canupdates"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long canupdates
     * }
     */
    public static final OfLong canupdates$layout() {
        return canupdates$LAYOUT;
    }

    private static final long canupdates$OFFSET = $LAYOUT.byteOffset(groupElement("canupdates"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long canupdates
     * }
     */
    public static final long canupdates$offset() {
        return canupdates$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long canupdates
     * }
     */
    public static long canupdates(MemorySegment struct) {
        return struct.get(canupdates$LAYOUT, canupdates$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long canupdates
     * }
     */
    public static void canupdates(MemorySegment struct, long fieldValue) {
        struct.set(canupdates$LAYOUT, canupdates$OFFSET, fieldValue);
    }

    private static final OfLong invapplics$LAYOUT = (OfLong)$LAYOUT.select(groupElement("invapplics"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long invapplics
     * }
     */
    public static final OfLong invapplics$layout() {
        return invapplics$LAYOUT;
    }

    private static final long invapplics$OFFSET = $LAYOUT.byteOffset(groupElement("invapplics"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long invapplics
     * }
     */
    public static final long invapplics$offset() {
        return invapplics$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long invapplics
     * }
     */
    public static long invapplics(MemorySegment struct) {
        return struct.get(invapplics$LAYOUT, invapplics$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long invapplics
     * }
     */
    public static void invapplics(MemorySegment struct, long fieldValue) {
        struct.set(invapplics$LAYOUT, invapplics$OFFSET, fieldValue);
    }

    private static final OfLong invsuccesses$LAYOUT = (OfLong)$LAYOUT.select(groupElement("invsuccesses"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long invsuccesses
     * }
     */
    public static final OfLong invsuccesses$layout() {
        return invsuccesses$LAYOUT;
    }

    private static final long invsuccesses$OFFSET = $LAYOUT.byteOffset(groupElement("invsuccesses"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long invsuccesses
     * }
     */
    public static final long invsuccesses$offset() {
        return invsuccesses$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long invsuccesses
     * }
     */
    public static long invsuccesses(MemorySegment struct) {
        return struct.get(invsuccesses$LAYOUT, invsuccesses$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long invsuccesses
     * }
     */
    public static void invsuccesses(MemorySegment struct, long fieldValue) {
        struct.set(invsuccesses$LAYOUT, invsuccesses$OFFSET, fieldValue);
    }

    private static final OfInt invarsuclevel$LAYOUT = (OfInt)$LAYOUT.select(groupElement("invarsuclevel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int invarsuclevel
     * }
     */
    public static final OfInt invarsuclevel$layout() {
        return invarsuclevel$LAYOUT;
    }

    private static final long invarsuclevel$OFFSET = $LAYOUT.byteOffset(groupElement("invarsuclevel"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int invarsuclevel
     * }
     */
    public static final long invarsuclevel$offset() {
        return invarsuclevel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int invarsuclevel
     * }
     */
    public static int invarsuclevel(MemorySegment struct) {
        return struct.get(invarsuclevel$LAYOUT, invarsuclevel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int invarsuclevel
     * }
     */
    public static void invarsuclevel(MemorySegment struct, int fieldValue) {
        struct.set(invarsuclevel$LAYOUT, invarsuclevel$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

