// Generated by jextract

package ua.ihromant.jnauty.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TracesStats {
 *     double grpsize1;
 *     int grpsize2;
 *     int numgenerators;
 *     int numorbits;
 *     int treedepth;
 *     int canupdates;
 *     int errstatus;
 *     unsigned long numnodes;
 *     unsigned long interrupted;
 *     unsigned long peaknodes;
 * }
 * }
 */
public class TracesStats {

    TracesStats() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        NautyTraces.C_DOUBLE.withName("grpsize1"),
        NautyTraces.C_INT.withName("grpsize2"),
        NautyTraces.C_INT.withName("numgenerators"),
        NautyTraces.C_INT.withName("numorbits"),
        NautyTraces.C_INT.withName("treedepth"),
        NautyTraces.C_INT.withName("canupdates"),
        NautyTraces.C_INT.withName("errstatus"),
        NautyTraces.C_LONG.withName("numnodes"),
        NautyTraces.C_LONG.withName("interrupted"),
        NautyTraces.C_LONG.withName("peaknodes")
    ).withName("TracesStats");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble grpsize1$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("grpsize1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double grpsize1
     * }
     */
    public static final OfDouble grpsize1$layout() {
        return grpsize1$LAYOUT;
    }

    private static final long grpsize1$OFFSET = $LAYOUT.byteOffset(groupElement("grpsize1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double grpsize1
     * }
     */
    public static final long grpsize1$offset() {
        return grpsize1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double grpsize1
     * }
     */
    public static double grpsize1(MemorySegment struct) {
        return struct.get(grpsize1$LAYOUT, grpsize1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double grpsize1
     * }
     */
    public static void grpsize1(MemorySegment struct, double fieldValue) {
        struct.set(grpsize1$LAYOUT, grpsize1$OFFSET, fieldValue);
    }

    private static final OfInt grpsize2$LAYOUT = (OfInt)$LAYOUT.select(groupElement("grpsize2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int grpsize2
     * }
     */
    public static final OfInt grpsize2$layout() {
        return grpsize2$LAYOUT;
    }

    private static final long grpsize2$OFFSET = $LAYOUT.byteOffset(groupElement("grpsize2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int grpsize2
     * }
     */
    public static final long grpsize2$offset() {
        return grpsize2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int grpsize2
     * }
     */
    public static int grpsize2(MemorySegment struct) {
        return struct.get(grpsize2$LAYOUT, grpsize2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int grpsize2
     * }
     */
    public static void grpsize2(MemorySegment struct, int fieldValue) {
        struct.set(grpsize2$LAYOUT, grpsize2$OFFSET, fieldValue);
    }

    private static final OfInt numgenerators$LAYOUT = (OfInt)$LAYOUT.select(groupElement("numgenerators"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int numgenerators
     * }
     */
    public static final OfInt numgenerators$layout() {
        return numgenerators$LAYOUT;
    }

    private static final long numgenerators$OFFSET = $LAYOUT.byteOffset(groupElement("numgenerators"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int numgenerators
     * }
     */
    public static final long numgenerators$offset() {
        return numgenerators$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int numgenerators
     * }
     */
    public static int numgenerators(MemorySegment struct) {
        return struct.get(numgenerators$LAYOUT, numgenerators$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int numgenerators
     * }
     */
    public static void numgenerators(MemorySegment struct, int fieldValue) {
        struct.set(numgenerators$LAYOUT, numgenerators$OFFSET, fieldValue);
    }

    private static final OfInt numorbits$LAYOUT = (OfInt)$LAYOUT.select(groupElement("numorbits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int numorbits
     * }
     */
    public static final OfInt numorbits$layout() {
        return numorbits$LAYOUT;
    }

    private static final long numorbits$OFFSET = $LAYOUT.byteOffset(groupElement("numorbits"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int numorbits
     * }
     */
    public static final long numorbits$offset() {
        return numorbits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int numorbits
     * }
     */
    public static int numorbits(MemorySegment struct) {
        return struct.get(numorbits$LAYOUT, numorbits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int numorbits
     * }
     */
    public static void numorbits(MemorySegment struct, int fieldValue) {
        struct.set(numorbits$LAYOUT, numorbits$OFFSET, fieldValue);
    }

    private static final OfInt treedepth$LAYOUT = (OfInt)$LAYOUT.select(groupElement("treedepth"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int treedepth
     * }
     */
    public static final OfInt treedepth$layout() {
        return treedepth$LAYOUT;
    }

    private static final long treedepth$OFFSET = $LAYOUT.byteOffset(groupElement("treedepth"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int treedepth
     * }
     */
    public static final long treedepth$offset() {
        return treedepth$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int treedepth
     * }
     */
    public static int treedepth(MemorySegment struct) {
        return struct.get(treedepth$LAYOUT, treedepth$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int treedepth
     * }
     */
    public static void treedepth(MemorySegment struct, int fieldValue) {
        struct.set(treedepth$LAYOUT, treedepth$OFFSET, fieldValue);
    }

    private static final OfInt canupdates$LAYOUT = (OfInt)$LAYOUT.select(groupElement("canupdates"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int canupdates
     * }
     */
    public static final OfInt canupdates$layout() {
        return canupdates$LAYOUT;
    }

    private static final long canupdates$OFFSET = $LAYOUT.byteOffset(groupElement("canupdates"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int canupdates
     * }
     */
    public static final long canupdates$offset() {
        return canupdates$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int canupdates
     * }
     */
    public static int canupdates(MemorySegment struct) {
        return struct.get(canupdates$LAYOUT, canupdates$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int canupdates
     * }
     */
    public static void canupdates(MemorySegment struct, int fieldValue) {
        struct.set(canupdates$LAYOUT, canupdates$OFFSET, fieldValue);
    }

    private static final OfInt errstatus$LAYOUT = (OfInt)$LAYOUT.select(groupElement("errstatus"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int errstatus
     * }
     */
    public static final OfInt errstatus$layout() {
        return errstatus$LAYOUT;
    }

    private static final long errstatus$OFFSET = $LAYOUT.byteOffset(groupElement("errstatus"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int errstatus
     * }
     */
    public static final long errstatus$offset() {
        return errstatus$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int errstatus
     * }
     */
    public static int errstatus(MemorySegment struct) {
        return struct.get(errstatus$LAYOUT, errstatus$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int errstatus
     * }
     */
    public static void errstatus(MemorySegment struct, int fieldValue) {
        struct.set(errstatus$LAYOUT, errstatus$OFFSET, fieldValue);
    }

    private static final OfLong numnodes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("numnodes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long numnodes
     * }
     */
    public static final OfLong numnodes$layout() {
        return numnodes$LAYOUT;
    }

    private static final long numnodes$OFFSET = $LAYOUT.byteOffset(groupElement("numnodes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long numnodes
     * }
     */
    public static final long numnodes$offset() {
        return numnodes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long numnodes
     * }
     */
    public static long numnodes(MemorySegment struct) {
        return struct.get(numnodes$LAYOUT, numnodes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long numnodes
     * }
     */
    public static void numnodes(MemorySegment struct, long fieldValue) {
        struct.set(numnodes$LAYOUT, numnodes$OFFSET, fieldValue);
    }

    private static final OfLong interrupted$LAYOUT = (OfLong)$LAYOUT.select(groupElement("interrupted"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long interrupted
     * }
     */
    public static final OfLong interrupted$layout() {
        return interrupted$LAYOUT;
    }

    private static final long interrupted$OFFSET = $LAYOUT.byteOffset(groupElement("interrupted"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long interrupted
     * }
     */
    public static final long interrupted$offset() {
        return interrupted$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long interrupted
     * }
     */
    public static long interrupted(MemorySegment struct) {
        return struct.get(interrupted$LAYOUT, interrupted$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long interrupted
     * }
     */
    public static void interrupted(MemorySegment struct, long fieldValue) {
        struct.set(interrupted$LAYOUT, interrupted$OFFSET, fieldValue);
    }

    private static final OfLong peaknodes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("peaknodes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long peaknodes
     * }
     */
    public static final OfLong peaknodes$layout() {
        return peaknodes$LAYOUT;
    }

    private static final long peaknodes$OFFSET = $LAYOUT.byteOffset(groupElement("peaknodes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long peaknodes
     * }
     */
    public static final long peaknodes$offset() {
        return peaknodes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long peaknodes
     * }
     */
    public static long peaknodes(MemorySegment struct) {
        return struct.get(peaknodes$LAYOUT, peaknodes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long peaknodes
     * }
     */
    public static void peaknodes(MemorySegment struct, long fieldValue) {
        struct.set(peaknodes$LAYOUT, peaknodes$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

